In [15]:
#Import Libraries
import pandas as pd
import sqlite3

In [19]:
#Load Dataset
df = pd.read_csv('data.csv', encoding='ISO-8859-1')

print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

      InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/2010 8:26       2.55     17850.0  United Kingdom
1  12/1/2010 8:26       3.39     17850.0  United Kingdom
2  12/1/2010 8:26       2.75     17850.0  United Kingdom
3  12/1/2010 8:26       3.39     17850.0  United Kingdom
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

In [13]:
#Create SQLite Database
import pandas as pd
df = pd.read_csv('data.csv', encoding='ISO-8859-1')

print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

      InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/2010 8:26       2.55     17850.0  United Kingdom
1  12/1/2010 8:26       3.39     17850.0  United Kingdom
2  12/1/2010 8:26       2.75     17850.0  United Kingdom
3  12/1/2010 8:26       3.39     17850.0  United Kingdom
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

In [23]:
#SQL Queries
conn = sqlite3.connect(':memory:')  # Create an in-memory SQLite database
df.to_sql('ecommerce_data', conn, index=False, if_exists='replace') # Write DataFrame to SQL table

query = """
SELECT *
FROM ecommerce_data
LIMIT 10;
"""

pd.read_sql(query, conn)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [24]:
#WHERE Query
query = """
SELECT *
FROM ecommerce_data
WHERE Quantity > 10;
"""

pd.read_sql(query, conn)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom
1,536370,22728,ALARM CLOCK BAKELIKE PINK,24,12/1/2010 8:45,3.75,12583.0,France
2,536370,22727,ALARM CLOCK BAKELIKE RED,24,12/1/2010 8:45,3.75,12583.0,France
3,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,12/1/2010 8:45,3.75,12583.0,France
4,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,12/1/2010 8:45,0.85,12583.0,France
...,...,...,...,...,...,...,...,...
132626,581587,22631,CIRCUS PARADE LUNCH BOX,12,12/9/2011 12:50,1.95,12680.0,France
132627,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,12/9/2011 12:50,1.65,12680.0,France
132628,581587,22555,PLASTERS IN TIN STRONGMAN,12,12/9/2011 12:50,1.65,12680.0,France
132629,581587,22629,SPACEBOY LUNCH BOX,12,12/9/2011 12:50,1.95,12680.0,France
132630,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France

In [25]:
#GROUP BY Query
query = """
SELECT Country, SUM(Quantity) AS Total_Quantity
FROM ecommerce_data
GROUP BY Country;
"""

pd.read_sql(query, conn)

                 Country  Total_Quantity
0              Australia           83653
1                Austria            4827
2                Bahrain             260
3                Belgium           23152
4                 Brazil             356
5                 Canada            2763
6        Channel Islands            9479
7                 Cyprus            6317
8         Czech Republic             592
9                Denmark            8188
10                  EIRE          142637
11    European Community             497
12               Finland           10666
13                France          110480
14               Germany          117448
15                Greece            1556
16             Hong Kong            4769
17               Iceland            2458
18                Israel            4353
19                 Italy            7999
20                 Japan           25218
21               Lebanon             386
22             Lithuania             652
23                 Malta             944
24           Netherlands          200128
25                Norway           19247
26                Poland            3653
27              Portugal           16180
28                   RSA             352
29          Saudi Arabia              75
30             Singapore            5234
31                 Spain           26824
32                Sweden           35637
33           Switzerland           30325
34                   USA            1034
35  United Arab Emirates             982
36        United Kingdom         4263829
37           Unspecified            3300

In [26]:
#ORDER BY Query
query = """
SELECT Description, UnitPrice
FROM ecommerce_data
ORDER BY UnitPrice DESC;
"""

pd.read_sql(query, conn)

                         Description  UnitPrice
0                             Manual   38970.00
1                         AMAZON FEE   17836.46
2                         AMAZON FEE   16888.02
3                         AMAZON FEE   16453.71
4                         AMAZON FEE   13541.33
...                              ...        ...
541904  POLYESTER FILLER PAD 40x40cm       0.00
541905                          None       0.00
541906                       smashed       0.00
541907               Adjust bad debt  -11062.06
541908               Adjust bad debt  -11062.06

[541909 rows x 2 columns]

In [27]:
#AVG Function
query = """
SELECT AVG(UnitPrice) AS Average_Price
FROM ecommerce_data;
"""

pd.read_sql(query, conn)

   Average_Price
0       4.611114

In [28]:
#Top Products
query = """
SELECT Description, SUM(Quantity) AS Total_Sales
FROM ecommerce_data
GROUP BY Description
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                          Description  Total_Sales
0   WORLD WAR 2 GLIDERS ASSTD DESIGNS        53847
1             JUMBO BAG RED RETROSPOT        47363
2       ASSORTED COLOUR BIRD ORNAMENT        36381
3                      POPCORN HOLDER        36334
4     PACK OF 72 RETROSPOT CAKE CASES        36039
5  WHITE HANGING HEART T-LIGHT HOLDER        35317
6                  RABBIT NIGHT LIGHT        30680
7             MINI PAINT SET VINTAGE         26437
8          PACK OF 12 LONDON TISSUES         26315
9  PACK OF 60 PINK PAISLEY CAKE CASES        24753

In [29]:
#Subquery
query = """
SELECT *
FROM ecommerce_data
WHERE UnitPrice > (
    SELECT AVG(UnitPrice)
    FROM ecommerce_data
);
"""

pd.read_sql(query, conn)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
1,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12/1/2010 8:34,4.95,13047.0,United Kingdom
2,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/2010 8:34,9.95,13047.0,United Kingdom
3,536367,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
4,536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
...,...,...,...,...,...,...,...,...
112644,581580,37500,TEA TIME TEAPOT IN GIFT BOX,1,12/9/2011 12:20,4.95,12748.0,United Kingdom
112645,581585,23356,LOVE HOT WATER BOTTLE,3,12/9/2011 12:31,5.95,15804.0,United Kingdom
112646,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,12/9/2011 12:49,8.95,13113.0,United Kingdom
112647,581586,20685,DOORMAT RED RETROSPOT,10,12/9/2011 12:49,7.08,13113.0,United Kingdom
112648,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [30]:
#Create View
query = """
CREATE VIEW high_sales_products AS
SELECT Description, SUM(Quantity) AS Total_Quantity
FROM ecommerce_data
GROUP BY Description;
"""

conn.execute(query)

print("VIEW CREATED SUCCESSFULLY")

VIEW CREATED SUCCESSFULLY

In [31]:
#NULL Handling
query = """
SELECT *
FROM ecommerce_data
WHERE CustomerID IS NULL;
"""

pd.read_sql(query, conn)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536414,22139,None,56,12/1/2010 11:52,0.00,None,United Kingdom
1,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,None,United Kingdom
2,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,None,United Kingdom
3,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,None,United Kingdom
4,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,None,United Kingdom
...,...,...,...,...,...,...,...,...
135075,581498,85099B,JUMBO BAG RED RETROSPOT,5,12/9/2011 10:26,4.13,None,United Kingdom
135076,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,12/9/2011 10:26,4.13,None,United Kingdom
135077,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,12/9/2011 10:26,4.96,None,United Kingdom
135078,581498,85174,S/4 CACTI CANDLES,1,12/9/2011 10:26,10.79,None,United Kingdom
135079,581498,DOT,DOTCOM POSTAGE,1,12/9/2011 10:26,1714.17,None,United Kingdom

In [32]:
#Create Index
query = """
CREATE INDEX idx_country
ON ecommerce_data(Country);
"""

conn.execute(query)

print("INDEX CREATED SUCCESSFULLY")

INDEX CREATED SUCCESSFULLY